### ISSUE TITLE
Where is zkvmpil?

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-doc#8]
[zkvmpil](https://github.com/hermeznetwork/zkvmpil): PIL source code for the zkVM (state-machines)
Is `zkvmpil`  repo open now?

**Comment by hecmas** [comment]
It has been integrated within the [zkevm-proverjs](https://github.com/0xPolygonHermez/zkevm-proverjs) repo. 
You can find it in the [pil](https://github.com/0xPolygonHermez/zkevm-proverjs/tree/main/pil) folder.

**Comment by 3for** [comment]
Thanks. @hecmas
